/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_wuyukai_ndkdemo_Command */

#ifndef _Included_com_example_wuyukai_ndkdemo_Command
#define _Included_com_example_wuyukai_ndkdemo_Command
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
